# Generated by Django 4.1.2 on 2022-11-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reviews_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='products',
            new_name='product',
        ),
    ]
